spring:
  profiles:
    active: uppercase
  application:
    name: FlashCardsRebased
  banner:
    location: logo-app
    charset: UTF-8
  h2:
    console:
      path: /my-console
      enabled: true
  datasource:
    url: jdbc:h2:file:./db/books;DATABASE_TO_UPPER=false;
    driverClassName: org.h2.Driver
    username: emik
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl